// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TavernAPI.Models;

namespace TavernAPI.Migrations
{
    [DbContext(typeof(TavernContext))]
    partial class TavernContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("TavernAPI.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChaMod");

                    b.Property<int>("Charisma");

                    b.Property<int>("ConMod");

                    b.Property<int>("Constitution");

                    b.Property<int>("DexMod");

                    b.Property<int>("Dexterity");

                    b.Property<int>("HitPoints");

                    b.Property<int>("IntMod");

                    b.Property<int>("Intelligence");

                    b.Property<int>("PlayerId");

                    b.Property<string>("SavingThrows");

                    b.Property<string>("Skills");

                    b.Property<int>("StrMod");

                    b.Property<int>("Strength");

                    b.Property<int>("WisMod");

                    b.Property<int>("Wisdom");

                    b.Property<string>("alignment");

                    b.Property<string>("background");

                    b.Property<string>("charClass");

                    b.Property<string>("name");

                    b.Property<string>("race");

                    b.Property<string>("size");

                    b.Property<int>("speed");

                    b.Property<string>("subRace");

                    b.HasKey("CharacterId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("TavernAPI.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.Property<string>("PlayerName");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("TavernAPI.Models.Character", b =>
                {
                    b.HasOne("TavernAPI.Models.Player")
                        .WithMany("charList")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
